env:
  global:
    - CC_TEST_REPORTER_ID=25b6bf1f9b4027de4583732016316df1990d79e10e56cc8fdf44368fabf4f122
language: node_js
node_js:
  - 8.2.1
dist: trusty
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

